[package]
name = "oth"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
regex = "1"
shlex = "1.3"
skim = { version = "2.0.0", default-features = false, features = ["cli"] }
